DELIMITER $$

CREATE TRIGGER update_timestamp_country
BEFORE UPDATE ON country
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_city
BEFORE UPDATE ON city
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_dependency
BEFORE UPDATE ON dependency
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_partner
BEFORE UPDATE ON partner
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_users
BEFORE UPDATE ON users
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_groups
BEFORE UPDATE ON `groups`
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_user_group
BEFORE UPDATE ON user_group
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_case_type
BEFORE UPDATE ON case_type
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_case
BEFORE UPDATE ON `case`
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_appointment
BEFORE UPDATE ON appointment
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_notes
BEFORE UPDATE ON notes
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

CREATE TRIGGER update_timestamp_attachment
BEFORE UPDATE ON attachment
FOR EACH ROW
DETERMINISTIC
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END$$

DELIMITER ;